version: "3"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      API_HOST: http://209.38.231.148:8000

  backend:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    image: backend-river-model
    volumes:
      - ../backend/app:/app
      - ../backend/tests:/tests
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
      - SECRET_KEY=aksdnaksfnaksfmasnfan
      - ALGORITHM=HS256
    command: /bin/sh -c "alembic upgrade head && 
                        uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app_net

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - dbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net:
    external: true
    name: app_net

volumes:
  dbdata:
