FROM node:18-alpine as build
WORKDIR /app

RUN npm install -g @angular/cli

COPY ./package.json .
RUN npm install

COPY . .
RUN ng build

FROM nginx:1.17.6-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html

CMD ["/bin/sh", "-c", "envsubst < /usr/share/nginx/html/assets/app-config-template.json | tee > /usr/share/nginx/html/assets/app-config.json && exec nginx -g 'daemon off;'"]
