"""Add default researcher and roles

Revision ID: 00fab0627eba
Revises: 72c25160ded7
Create Date: 2023-04-22 13:20:06.040993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision = '00fab0627eba'
down_revision = '72c25160ded7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("INSERT INTO auth.roles (name, is_active) "
                         "VALUES ('viewer', TRUE), ('researcher', TRUE);"))
    conn.execute(sa.text(
        "INSERT INTO auth.users (login, password, role_id, is_active) "
        "VALUES ("
        "'admin', "
        "'$2b$12$di0ZzFzTa3nqQj0/XSBABukqnXKDZHTror5FmzcsVQC1pozc04Mly', "
        "(SELECT id FROM auth.roles WHERE name = 'researcher'), "
        "TRUE"
        ");"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM auth.users WHERE login = 'admin';"))
    conn.execute(sa.text("DELETE FROM auth.roles WHERE name = 'viewer' OR name = 'researcher'"))
    # ### end Alembic commands ###
