"""Add river model

Revision ID: 335ac8591b3d
Revises: 06a918a379c8
Create Date: 2023-05-03 18:27:59.475683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335ac8591b3d'
down_revision = '06a918a379c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rivers')
    # ### end Alembic commands ###
