"""Add association table LocationChemicalElements

Revision ID: 3f074bfdde6e
Revises: f0156ec83e75
Create Date: 2023-05-12 17:02:56.151333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f074bfdde6e'
down_revision = 'f0156ec83e75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_chemical_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('chemical_element_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_element_id'], ['chemical_elements.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'chemical_element_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_chemical_elements')
    # ### end Alembic commands ###
