"""Create auth schema

Revision ID: 4a2a5ff524de
Revises: 
Create Date: 2023-04-06 21:01:42.451453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2a5ff524de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text('CREATE SCHEMA IF NOT EXISTS auth;'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text('DROP SCHEMA IF EXISTS auth;'))
    # ### end Alembic commands ###
