"""setting database up to date

Revision ID: 4b96f1bb4d7f
Revises: 335ac8591b3d
Create Date: 2023-05-07 07:40:03.357968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b96f1bb4d7f'
down_revision = '335ac8591b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('units', sa.String(length=20), nullable=True),
    sa.Column('timedelta_decay', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical_elements')
    # ### end Alembic commands ###
