"""Fixed problem with ChemicalElement schema

Revision ID: 88d341c9aa35
Revises: b598b15cbf72
Create Date: 2023-05-06 16:52:32.730052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88d341c9aa35'
down_revision = 'b598b15cbf72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chemical_elements', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('chemical_elements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_chemical_elements_id', table_name='chemical_elements')
    op.drop_index('ix_chemical_elements_name', table_name='chemical_elements')
    op.create_unique_constraint(None, 'chemical_elements', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chemical_elements', type_='unique')
    op.create_index('ix_chemical_elements_name', 'chemical_elements', ['name'], unique=False)
    op.create_index('ix_chemical_elements_id', 'chemical_elements', ['id'], unique=False)
    op.alter_column('chemical_elements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chemical_elements', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
