"""Created entity ChemicalElement

Revision ID: b598b15cbf72
Revises: 06a918a379c8
Create Date: 2023-05-02 18:06:04.962357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b598b15cbf72'
down_revision = '335ac8591b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('units', sa.String(length=20), nullable=True),
    sa.Column('timedelta_decay', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_elements_id'), 'chemical_elements', ['id'], unique=False)
    op.create_index(op.f('ix_chemical_elements_name'), 'chemical_elements', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemical_elements_name'), table_name='chemical_elements')
    op.drop_index(op.f('ix_chemical_elements_id'), table_name='chemical_elements')
    op.drop_table('chemical_elements')
    # ### end Alembic commands ###
