name: Deploy
on:
  push:
    branches:
    - 'ci-cd'
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          cd /opt/app/RiverModel
          git checkout master
          git pull
          cd backend
          docker compose up -d --build
